project:
  type: website

website:
  title: "Shiny for Python Workshop"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - getting-started.qmd
      - reactivity.qmd
      - side-effects.qmd
      - modules.qmd
      - styling.qmd

filters:
  - shinylive

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



