project:
  type: website

website:
  title: "."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - getting-started.qmd
      - reactivity.qmd
      - side-effects.qmd
      - modules.qmd
      - styling.qmd

filters:
  - shinylive

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



