project:
  type: website

website:
  title: "Shiny for Python Workshop"
  sidebar:
    contents:
      - section: "Session 1"
        contents:
          - slides/getting-started.qmd
          - section: "Exercises"
            contents: 
            - exercises/1-hello-world.qmd
            - exercises/2-debug.qmd
            - exercises/3-add-filter.qmd
            - exercises/4-add-plot.qmd
      - section: "Session 2"
        contents:
          - slides/reactivity.qmd
          - section: "Exercises"
            contents: 
            - exercises/5-reactivity.qmd
            - exercises/6-reactive-event.qmd
            - exercises/7-reactive-effects.qmd
      - section: "Session 3"
        contents:
          - slides/ui-customization.qmd
          - section: "Exercises"
            contents: 
            - exercises/1-hello-world.qmd
            - exercises/2-debug.qmd
            - exercises/3-add-filter.qmd
            - exercises/4-add-plot.qmd
      
  navbar:
    tools: 
      - icon: github
        href: https://github.com/posit-dev/shiny-python-workshop-2023
      - icon: fa-dicord
        href: https://discord.gg/AQVJzG2bnN
    left:
      - href: index.qmd
        text: Home

filters:
  - shinylive

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



