project:
  type: website

website:
  title: "Shiny for Python Workshop"
  sidebar:
    contents:
      - section: "Documents"
        contents:        
          - docs/getting-started.qmd
          - docs/reactivity.qmd
          - docs/reactive-side-effects.qmd
          - docs/ui-customization.qmd
      - section: "Slides"
        contents:
          - slides/getting-started.qmd
  navbar:

    tools: 
      - icon: github
        href: https://github.com/rstudio/shiny-python-workshop-2023
      - icon: fa-dicord
        href: https://discord.gg/AQVJzG2bnN
    left:
      - href: index.qmd
        text: Home

filters:
  - shinylive

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



